name: ci

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    id-token: write
    packages: write
    attestations: write

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
    container:
        name: "docling C9S dev container"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set up container metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ${{ env.IMAGE_NAME }}
              env:
                  DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

            - name: Build container image
              id: build
              uses: docker/build-push-action@v5
              with:
                  file: ./containers/docling/Containerfile
                  context: ./containers/docling/
                  load: false
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  annotations: ${{ steps.meta.outputs.annotations }}
                  cache-from: type=gha
                  cache-to: type=gha

            - name: Attest
              uses: actions/attest-build-provenance@v1
              id: attest
              with:
                  subject-name: ${{ env.IMAGE_NAME }}
                  subject-digest: ${{ steps.build.outputs.digest }}
                  push-to-registry: true
